services:
  - docker
language: bash

addons:
  apt:
    packages:
    - docker-ce

env:
  matrix:
  - CONTAINER=debian-unstable-ppc
  - CONTAINER=debian-buster-arm
  - CONTAINER=debian-buster-aarch64

before_install:
- docker run --rm --privileged multiarch/qemu-user-static:register --reset

script:
- travis_retry docker build -t pqclean/$CONTAINER $CONTAINER

deploy:
  provider: script
  script:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push pqclean/$CONTAINER
  on:
    branch: master
#  vim: set ft=yaml ts=4 sw=2 tw=0 et :
